const PROBLEMS = [
  // ===== BEGINNER =====
  {
    id: 1, difficulty: 'beginner', title: '現物の基本',
    description: '相手の捨て牌と同じ牌は絶対安全！',
    opponentDiscards: ['9m', '3p', '6s', '1z'],
    hand: [
      { tile: '9m',  safe: true,  safeType: 'genzai',  reason: '現物（相手が捨てた牌）' },
      { tile: '1z',  safe: true,  safeType: 'genzai',  reason: '現物（相手が捨てた牌）' },
      { tile: '5m',  safe: false, reason: '振り込み！6m-7m の両面待ち' },
      { tile: '8m',  safe: false, reason: '振り込み！6m-7m の両面待ち' },
      { tile: '4p',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '7s',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '3z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['5m', '8m'], waitShape: '6m-7m の両面待ち',
    explanation: '9m と東（1z）は現物で安全。\n5m と 8m が待ち牌（6m-7m の両面）！',
    yaku: '断么九', yakuValue: 1,
    playerYaku: '平和', playerYakuValue: 1,
  },
  {
    id: 2, difficulty: 'beginner', title: '字牌は現物で安全',
    description: '字牌も捨ててあれば現物！',
    opponentDiscards: ['5z', '4m', '3p', '2s'],
    hand: [
      { tile: '5z',  safe: true,  safeType: 'genzai',  reason: '現物（白）' },
      { tile: '4m',  safe: true,  safeType: 'genzai',  reason: '現物' },
      { tile: '6s',  safe: false, reason: '振り込み！7s-8s の両面待ち' },
      { tile: '9s',  safe: false, reason: '振り込み！7s-8s の両面待ち' },
      { tile: '1m',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '4p',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '4z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['6s', '9s'], waitShape: '7s-8s の両面待ち',
    explanation: '白（5z）と 4m は現物で安全。\n6s と 9s が待ち牌（7s-8s の両面）！',
    yaku: '断么九', yakuValue: 1,
    playerYaku: 'タンヤオ', playerYakuValue: 1,
  },
  {
    id: 3, difficulty: 'beginner', title: '現物を見つけよう',
    description: '捨て牌の中に安全牌のヒントがある！',
    opponentDiscards: ['6m', '2p', '5s', '2z'],
    hand: [
      { tile: '6m',  safe: true,  safeType: 'genzai',  reason: '現物' },
      { tile: '2z',  safe: true,  safeType: 'genzai',  reason: '現物（南）' },
      { tile: '3p',  safe: false, reason: '振り込み！4p-5p の両面待ち' },
      { tile: '6p',  safe: false, reason: '振り込み！4p-5p の両面待ち' },
      { tile: '8m',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '7s',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '6z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['3p', '6p'], waitShape: '4p-5p の両面待ち',
    explanation: '6m と南（2z）は現物で安全。\n3p と 6p が待ち牌（4p-5p の両面）！',
    yaku: '平和', yakuValue: 1,
    playerYaku: '門前清自摸和', playerYakuValue: 1,
  },
  {
    id: 4, difficulty: 'beginner', title: '危険牌は1枚だけ？',
    description: '単騎待ちは1種類だけが危険！',
    opponentDiscards: ['1m', '9p', '8s', '3z'],
    hand: [
      { tile: '1m',  safe: true,  safeType: 'genzai',  reason: '現物' },
      { tile: '3z',  safe: true,  safeType: 'genzai',  reason: '現物（西）' },
      { tile: '8p',  safe: false, reason: '振り込み！8p の単騎待ち' },
      { tile: '3m',  safe: true,  safeType: 'unknown', reason: '単騎待ち：危険牌は8pの1種類のみ' },
      { tile: '5p',  safe: true,  safeType: 'unknown', reason: '単騎待ち：危険牌は8pの1種類のみ' },
      { tile: '4s',  safe: true,  safeType: 'unknown', reason: '単騎待ち：危険牌は8pの1種類のみ' },
      { tile: '6z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['8p'], waitShape: '8p 単騎待ち',
    explanation: '1m と西（3z）は現物で安全。\n危険牌は 8p だけ！単騎待ちの罠に注意。',
    yaku: '七対子', yakuValue: 2,
    playerYaku: 'リーチ', playerYakuValue: 1,
  },
  {
    id: 5, difficulty: 'beginner', title: '危険牌は複数あるかも',
    description: '手牌に危険牌が 2 枚以上あることも！',
    opponentDiscards: ['7m', '4p', '2s', '4z'],
    hand: [
      { tile: '7m',  safe: true,  safeType: 'genzai',  reason: '現物' },
      { tile: '4z',  safe: true,  safeType: 'genzai',  reason: '現物（北）' },
      { tile: '3s',  safe: false, reason: '振り込み！4s-5s の両面待ち' },
      { tile: '6s',  safe: false, reason: '振り込み！4s-5s の両面待ち' },
      { tile: '9m',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '1p',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '1z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['3s', '6s'], waitShape: '4s-5s の両面待ち',
    explanation: '7m と北（4z）は現物で安全。\n3s と 6s が待ち牌（4s-5s の両面）！',
    yaku: '断么九', yakuValue: 1,
    playerYaku: '断么九', playerYakuValue: 1,
  },

  // ===== MEDIUM =====
  {
    id: 6, difficulty: 'medium', title: '筋（スジ）読みの基本',
    description: '4m が捨ててある → 1m と 7m は筋で比較的安全',
    opponentDiscards: ['4m', '3p', '8s', '1z', '3z'],
    hand: [
      { tile: '1m',  safe: true,  safeType: 'suji',    reason: '4m の筋（スジ）で安全' },
      { tile: '7m',  safe: true,  safeType: 'suji',    reason: '4m の筋（スジ）で安全' },
      { tile: '5p',  safe: false, reason: '振り込み！6p-7p の両面待ち' },
      { tile: '8p',  safe: false, reason: '振り込み！6p-7p の両面待ち' },
      { tile: '2s',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '4z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '5z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['5p', '8p'], waitShape: '6p-7p の両面待ち',
    explanation: '4m が捨て牌にある → 1m と 7m は「筋」で安全。\n5p と 8p が待ち（6p-7p の両面）。',
    yaku: '断么九', yakuValue: 1,
    playerYaku: '三色同順', playerYakuValue: 2,
  },
  {
    id: 7, difficulty: 'medium', title: '6 の筋を読む',
    description: '6m が捨ててある → 3m と 9m が筋',
    opponentDiscards: ['6m', '3p', '7s', '1z'],
    hand: [
      { tile: '3m',  safe: true,  safeType: 'suji',    reason: '6m の筋（スジ）で安全' },
      { tile: '9m',  safe: true,  safeType: 'suji',    reason: '6m の筋（スジ）で安全' },
      { tile: '4p',  safe: false, reason: '振り込み！5p-6p の両面待ち' },
      { tile: '7p',  safe: false, reason: '振り込み！5p-6p の両面待ち' },
      { tile: '2s',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '4z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '6z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['4p', '7p'], waitShape: '5p-6p の両面待ち',
    explanation: '6m が捨て牌にある → 3m と 9m は筋で安全。\n4p と 7p が待ち（5p-6p の両面）。',
    yaku: '一気通貫', yakuValue: 3,
    playerYaku: '平和', playerYakuValue: 2,
  },
  {
    id: 8, difficulty: 'medium', title: '複数の筋を組み合わせる',
    description: '複数の捨て牌から安全牌を導こう',
    opponentDiscards: ['3m', '6p', '9s', '2z', '3z'],
    hand: [
      { tile: '6m',  safe: true,  safeType: 'suji',    reason: '3m の筋（スジ）で安全' },
      { tile: '3p',  safe: true,  safeType: 'suji',    reason: '6p の筋（スジ）で安全' },
      { tile: '9p',  safe: true,  safeType: 'suji',    reason: '6p の筋（スジ）で安全' },
      { tile: '2s',  safe: false, reason: '振り込み！3s-4s の両面待ち' },
      { tile: '5s',  safe: false, reason: '振り込み！3s-4s の両面待ち' },
      { tile: '1m',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '5z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['2s', '5s'], waitShape: '3s-4s の両面待ち',
    explanation: '3m の筋→6m 安全、6p の筋→3p・9p 安全。\n2s と 5s が待ち（3s-4s の両面）。',
    yaku: '平和', yakuValue: 1,
    playerYaku: '一気通貫', playerYakuValue: 2,
  },
  {
    id: 9, difficulty: 'medium', title: '5 の筋を読む',
    description: '5m が捨ててある → 2m と 8m が筋',
    opponentDiscards: ['5m', '2p', '8s', '1z'],
    hand: [
      { tile: '2m',  safe: true,  safeType: 'suji',    reason: '5m の筋（スジ）で安全' },
      { tile: '8m',  safe: true,  safeType: 'suji',    reason: '5m の筋（スジ）で安全' },
      { tile: '2s',  safe: false, reason: '振り込み！3s-4s の両面待ち' },
      { tile: '5s',  safe: false, reason: '振り込み！3s-4s の両面待ち' },
      { tile: '4p',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '4z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '5z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['2s', '5s'], waitShape: '3s-4s の両面待ち',
    explanation: '5m の筋 → 2m と 8m は安全。\n2s と 5s が待ち（3s-4s の両面）！',
    yaku: '平和', yakuValue: 1,
    playerYaku: 'リーチ一発', playerYakuValue: 2,
  },
  {
    id: 10, difficulty: 'medium', title: '⚠️ 筋の罠！',
    description: '筋に見えても危険なことがある。スジは 100% じゃない！',
    opponentDiscards: ['3m', '7p', '5s', '2z'],
    hand: [
      { tile: '6m',  safe: false, reason: '振り込み！3m の筋に見えるが 6m 単騎待ちだった！', damage: 2 },
      { tile: '7m',  safe: true,  safeType: 'unknown', reason: '単騎待ち：危険牌は6mの1種類のみ' },
      { tile: '1s',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '4s',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '3p',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '3z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '5z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['6m'], waitShape: '6m 単騎待ち',
    explanation: '3m の筋なので 6m は安全に見えるが…\n相手は 6m の単騎待ち！スジも 100% ではない！',
    yaku: '七対子', yakuValue: 2,
    playerYaku: 'タンヤオ', playerYakuValue: 2,
  },

  // ===== ADVANCED =====
  {
    id: 11, difficulty: 'advanced', title: '複合待ち（三面張）に注意！',
    description: '相手の待ちが 3 種類になることがある',
    opponentDiscards: ['9m', '8s', '1z', '4z', '3z'],
    hand: [
      { tile: '1p',  safe: false, reason: '振り込み！2p-3p で 1p or 4p 待ち' },
      { tile: '4p',  safe: false, reason: '振り込み！2p-3p と 5p-6p の複合で 4p！' },
      { tile: '7p',  safe: false, reason: '振り込み！5p-6p で 4p or 7p 待ち' },
      { tile: '3m',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '6s',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '5z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '2z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['1p', '4p', '7p'], waitShape: '2p-3p-4p-5p-6p の三面張（1p・4p・7p 待ち）',
    explanation: '相手は三面張！2p-3p-4p-5p-6p で\n1p・4p・7p すべてが待ち牌！',
    yaku: '三色同順', yakuValue: 3,
    playerYaku: '七対子', playerYakuValue: 2,
  },
  {
    id: 12, difficulty: 'advanced', title: 'シャンポン（双碰）待ち',
    description: '2 種類の牌が同時に待ち牌になる！',
    opponentDiscards: ['8m', '3p', '7p', '6s', '1z'],
    hand: [
      { tile: '2m',  safe: false, reason: '振り込み！2m-2m のシャンポン片方' },
      { tile: '5p',  safe: false, reason: '振り込み！5p-5p のシャンポン片方' },
      { tile: '4m',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '8p',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '1s',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '2z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '5z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['2m', '5p'], waitShape: '2m-2m / 5p-5p のシャンポン待ち',
    explanation: 'シャンポン（双碰）は 2m・5p のどちらを\n振り込んでもアウト！両方危険。',
    yaku: '七対子', yakuValue: 2,
    playerYaku: '混一色', playerYakuValue: 3,
  },
  {
    id: 13, difficulty: 'advanced', title: 'カンチャン（間張）待ち',
    description: '間の牌を待つカンチャンは筋読みが効かない！',
    opponentDiscards: ['5m', '2p', '9s', '3z', '4z'],
    hand: [
      { tile: '7m',  safe: false, reason: '振り込み！6m-8m のカンチャン待ち' },
      { tile: '4p',  safe: false, reason: '振り込み！3p-5p のカンチャン待ち' },
      { tile: '1m',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '3s',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '2z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '5z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '6z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['7m', '4p'], waitShape: '6m-8m のカンチャン + 3p-5p のカンチャン',
    explanation: 'カンチャンは間の牌が待ち。筋では読めない！\n7m（6m-8m）と 4p（3p-5p）が複合カンチャン待ち。',
    yaku: '混一色', yakuValue: 3,
    playerYaku: '清一色', playerYakuValue: 3,
  },
  {
    id: 14, difficulty: 'advanced', title: '⚠️ 裏スジの罠',
    description: '筋に見える牌でも危険な「裏筋」がある',
    opponentDiscards: ['2m', '5m', '8p', '4s', '1z'],
    hand: [
      { tile: '8m',  safe: false, reason: '振り込み！5m の筋に見えるが 7m-9m のカンチャン（8m）だった！', damage: 2 },
      { tile: '7p',  safe: false, reason: '振り込み！6p-8p のカンチャン（7p）待ち', damage: 2 },
      { tile: '4m',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '2p',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '3s',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '2z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '5z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['8m', '7p'], waitShape: '7m-9m のカンチャン（8m）+ 6p-8p のカンチャン（7p）',
    explanation: '5m の筋なら 8m は安全そうだが…\n7m-9m のカンチャン！筋の裏が刺さることがある。',
    yaku: '一気通貫', yakuValue: 3,
    playerYaku: '三色同順', playerYakuValue: 3,
  },
  {
    id: 15, difficulty: 'advanced', title: '三面張を読め！',
    description: '索子の連続形で三面張が形成されることがある',
    opponentDiscards: ['3m', '6m', '4p', '7p', '1z'],
    hand: [
      { tile: '2s',  safe: false, reason: '振り込み！三面張の一つ（3s-4s の端）' },
      { tile: '5s',  safe: false, reason: '振り込み！三面張の中心' },
      { tile: '8s',  safe: false, reason: '振り込み！三面張の一つ（6s-7s の端）' },
      { tile: '9m',  safe: true,  safeType: 'suji',    reason: '6m の筋（スジ）で安全' },
      { tile: '1p',  safe: true,  safeType: 'suji',    reason: '4p の筋（スジ）で安全' },
      { tile: '5z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '2z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['2s', '5s', '8s'], waitShape: '3s-4s-5s-6s-7s の三面張（2s・5s・8s 待ち）',
    explanation: '3s-4s-5s-6s-7s は三面張！\n2s・5s・8s すべて危険。9m と 1p は筋で安全。',
    yaku: '清一色', yakuValue: 4,
    playerYaku: '国士無双', playerYakuValue: 4,
  },

  // ===== ADVANCED+ (現物ゼロ・スジ読み必須) =====
  {
    id: 16, difficulty: 'medium', title: '現物なし！筋牌で生き延びろ',
    description: '手牌に現物がない時こそ筋（スジ）読みが頼り！',
    opponentDiscards: ['7m', '9p', '2s', '5z', '6z'],
    hand: [
      { tile: '5p',  safe: false, reason: '振り込み！6p-7p の両面待ち' },
      { tile: '8p',  safe: false, reason: '振り込み！6p-7p の両面待ち' },
      { tile: '4m',  safe: true,  safeType: 'suji',    reason: '7m の筋（7-3=4）で安全' },
      { tile: '6p',  safe: true,  safeType: 'suji',    reason: '9p の筋（9-3=6）で安全' },
      { tile: '1z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '3s',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '9m',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
    ],
    waits: ['5p', '8p'], waitShape: '6p-7p の両面待ち',
    explanation: '捨て牌に現物なし！筋牌を使う。\n7m が捨ててある → 4m は筋で安全。\n9p が捨ててある → 6p は筋で安全。',
    yaku: '断么九', yakuValue: 1,
    playerYaku: '平和', playerYakuValue: 2,
  },
  {
    id: 17, difficulty: 'advanced', title: '⚠️ 筋の裏は危険！現物なし罠問題',
    description: '筋に見えても単騎待ちが刺さることがある',
    opponentDiscards: ['3m', '7p', '4s', '1z', '2z'],
    hand: [
      { tile: '6m',  safe: false, reason: '罠！3m の筋に見えるが 6m 単騎待ち！', damage: 2 },
      { tile: '4p',  safe: false, reason: '振り込み！5p-6p の両面待ち' },
      { tile: '7p',  safe: false, reason: '振り込み！7p は現物に見えるが 7p 単騎待ち！', damage: 2 },
      { tile: '1m',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '9s',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '5z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '6z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['6m', '4p', '7p'], waitShape: '6m 単騎 + 5p-6p 両面 + 7p 単騎（複合）',
    explanation: '3m の筋で 6m が安全そうに見えるが単騎待ち！\n7p も捨て牌に見えるが別コピーで単騎待ち！\n端牌（1m・9s）が比較的安全。現物がない時は端牌が頼り。',
    yaku: '混一色', yakuValue: 3,
    playerYaku: '七対子', playerYakuValue: 3,
  },
  {
    id: 18, difficulty: 'advanced', title: '完全スジ読み：現物ゼロ、罠だらけ',
    description: '筋と端牌で生き残れるか？超上級の降り問題',
    opponentDiscards: ['5m', '2p', '8s', '3z', '4z'],
    hand: [
      { tile: '2m',  safe: true,  safeType: 'suji',    reason: '5m の筋（5-3=2）で安全' },
      { tile: '8m',  safe: true,  safeType: 'suji',    reason: '5m の筋（5+3=8）で安全' },
      { tile: '5p',  safe: false, reason: '振り込み！4p-6p のカンチャン待ち' },
      { tile: '3p',  safe: false, reason: '罠！2p の筋に見えるが 3p-4p 形で 3p 待ち！', damage: 2 },
      { tile: '5s',  safe: false, reason: '振り込み！6s-7s の両面待ち' },
      { tile: '2s',  safe: false, reason: '振り込み！6s-7s の両面待ち? いや 1s-2s-3s 待ちだ！' },
      { tile: '1m',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
    ],
    waits: ['5p', '3p', '5s', '2s'], waitShape: '4p-6p カンチャン + 3p 単騎 + 6s-7s 両面 + 1s-3s 複合',
    explanation: '5m が捨ててある → 2m と 8m は筋で安全！\n2p の筋に見える 3p は単騎待ちの罠。\n5s・2s は複合待ちで危険。筋だけが頼りの超難問。',
    yaku: '国士無双', yakuValue: 5,
    playerYaku: '清一色', playerYakuValue: 4,
  },

  // ===== ADVANCED+ 追加問題 =====
  {
    id: 19, difficulty: 'medium', title: '二重スジを探せ！',
    description: '2 枚の捨て牌が同じ牌をスジとして示すことがある。それが一番安全！',
    opponentDiscards: ['2s', '8s', '4p', '3z', '6z'],
    hand: [
      { tile: '3z',  safe: true,  safeType: 'genzai',  reason: '現物（西）' },
      { tile: '6z',  safe: true,  safeType: 'genzai',  reason: '現物（発）' },
      { tile: '4p',  safe: true,  safeType: 'genzai',  reason: '現物' },
      { tile: '5s',  safe: true,  safeType: 'suji',    reason: '2s の筋（2+3=5）かつ 8s の筋（8-3=5）— 二重スジで安全！' },
      { tile: '6m',  safe: false, reason: '振り込み！7m-8m の両面待ち' },
      { tile: '9m',  safe: false, reason: '振り込み！7m-8m の両面待ち' },
      { tile: '1m',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
    ],
    waits: ['6m', '9m'], waitShape: '7m-8m の両面待ち',
    explanation: '2s の筋（2+3=5s）と 8s の筋（8-3=5s）が重なる！\n5s は二重スジで特に安全。\n6m と 9m が待ち（7m-8m の両面）。',
    yaku: '断么九', yakuValue: 1,
    playerYaku: '断么九', playerYakuValue: 1,
  },
  {
    id: 20, difficulty: 'medium', title: '大きい数字の筋',
    description: '7・8・9 が捨ててある → それぞれ 3 を引いた数が筋（片側だけ）',
    opponentDiscards: ['7p', '8s', '9m', '1z', '3z'],
    hand: [
      { tile: '1z',  safe: true,  safeType: 'genzai',  reason: '現物（東）' },
      { tile: '3z',  safe: true,  safeType: 'genzai',  reason: '現物（西）' },
      { tile: '4p',  safe: true,  safeType: 'suji',    reason: '7p の筋（7-3=4）で安全' },
      { tile: '5s',  safe: true,  safeType: 'suji',    reason: '8s の筋（8-3=5）で安全' },
      { tile: '6m',  safe: true,  safeType: 'suji',    reason: '9m の筋（9-3=6）で安全' },
      { tile: '1m',  safe: false, reason: '振り込み！2m-3m の両面待ち' },
      { tile: '4m',  safe: false, reason: '振り込み！2m-3m の両面待ち' },
    ],
    waits: ['1m', '4m'], waitShape: '2m-3m の両面待ち',
    explanation: '7p → 4p が筋。8s → 5s が筋。9m → 6m が筋。\n大きい数字（7・8・9）は左側に筋が 1 つだけ出る。\n1m と 4m が待ち（2m-3m の両面）。',
    yaku: '平和', yakuValue: 1,
    playerYaku: '断么九', playerYakuValue: 1,
  },
  {
    id: 21, difficulty: 'advanced', title: '⚠️ 字牌シャンポンの罠',
    description: '「字牌は安全」は通用しない！字牌同士でもシャンポン待ちになる',
    opponentDiscards: ['5m', '3p', '8s', '1z', '6z'],
    hand: [
      { tile: '1z',  safe: true,  safeType: 'genzai',  reason: '現物（東）' },
      { tile: '6z',  safe: true,  safeType: 'genzai',  reason: '現物（発）' },
      { tile: '2m',  safe: true,  safeType: 'suji',    reason: '5m の筋（5-3=2）で安全' },
      { tile: '8m',  safe: true,  safeType: 'suji',    reason: '5m の筋（5+3=8）で安全' },
      { tile: '9s',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '2z',  safe: false, reason: '振り込み！南-北（2z-4z）のシャンポン待ち！', damage: 2 },
      { tile: '4z',  safe: false, reason: '振り込み！南-北（2z-4z）のシャンポン待ち！', damage: 2 },
    ],
    waits: ['2z', '4z'], waitShape: '南-北（2z-4z）のシャンポン待ち',
    explanation: '南（2z）・北（4z）は字牌なのに危険！\n字牌同士のシャンポン待ちは珍しいが実在する。\n東（1z）・発（6z）は現物、2m・8m はスジで安全。',
    yaku: '混一色', yakuValue: 3,
    playerYaku: '七対子', playerYakuValue: 2,
  },
  {
    id: 22, difficulty: 'advanced', title: 'ノベタン（延べ単）待ち',
    description: '1-2-3-4 の 4 枚連続形は両端の 1 と 4 が待ち牌！',
    opponentDiscards: ['9m', '7p', '5s', '1z', '3z'],
    hand: [
      { tile: '1z',  safe: true,  safeType: 'genzai',  reason: '現物（東）' },
      { tile: '3z',  safe: true,  safeType: 'genzai',  reason: '現物（西）' },
      { tile: '4p',  safe: true,  safeType: 'suji',    reason: '7p の筋（7-3=4）で安全' },
      { tile: '2z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
      { tile: '6m',  safe: true,  safeType: 'unknown', reason: '消去法（読みでは判断できない）' },
      { tile: '1s',  safe: false, reason: '振り込み！1s-2s-3s-4s のノベタン（両端待ち）' },
      { tile: '4s',  safe: false, reason: '振り込み！1s-2s-3s-4s のノベタン（両端待ち）' },
    ],
    waits: ['1s', '4s'], waitShape: '1s-2s-3s-4s のノベタン（1s・4s 待ち）',
    explanation: '1s-2s-3s-4s の形は「ノベタン（延べ単）」！\n両端の 1s（対子 → 順子）と 4s（順子 → 対子）が待ち牌。\n4p は 7p の筋で安全。',
    yaku: '平和', yakuValue: 1,
    playerYaku: '断么九', playerYakuValue: 2,
  },
  {
    id: 23, difficulty: 'advanced', title: 'ペンチャン（辺張）待ち',
    description: '1-2 の端の形は 3 待ち、8-9 の形は 7 待ち！',
    opponentDiscards: ['5m', '3p', '2s', '4z', '5z'],
    hand: [
      { tile: '4z',  safe: true,  safeType: 'genzai',  reason: '現物（北）' },
      { tile: '5z',  safe: true,  safeType: 'genzai',  reason: '現物（白）' },
      { tile: '2m',  safe: true,  safeType: 'suji',    reason: '5m の筋（5-3=2）で安全' },
      { tile: '8m',  safe: true,  safeType: 'suji',    reason: '5m の筋（5+3=8）で安全' },
      { tile: '6p',  safe: true,  safeType: 'suji',    reason: '3p の筋（3+3=6）で安全' },
      { tile: '3s',  safe: false, reason: '振り込み！1s-2s のペンチャン（辺張）待ち' },
      { tile: '7s',  safe: false, reason: '振り込み！8s-9s のペンチャン（辺張）待ち' },
    ],
    waits: ['3s', '7s'], waitShape: '1s-2s のペンチャン（3s）+ 8s-9s のペンチャン（7s）',
    explanation: '1s-2s → 3s 待ち（ペンチャン）。\n8s-9s → 7s 待ち（ペンチャン）。\n複合ペンチャンで 3s・7s どちらも危険！',
    yaku: '一気通貫', yakuValue: 3,
    playerYaku: '混一色', playerYakuValue: 3,
  },
  {
    id: 24, difficulty: 'advanced', title: '⚠️ スジ罠 + 字牌端牌で守れ',
    description: '現物なし、スジの罠あり。字牌と端牌だけが安全への道',
    opponentDiscards: ['5p', '6m', '3s', '5z', '7z'],
    hand: [
      { tile: '5z',  safe: true,  safeType: 'genzai',  reason: '現物（白）' },
      { tile: '7z',  safe: true,  safeType: 'genzai',  reason: '現物（中）' },
      { tile: '8p',  safe: false, reason: '罠！5p の筋（5+3=8）に見えるが 8p 単騎待ち！', damage: 2 },
      { tile: '4p',  safe: false, reason: '振り込み！3p-5p のカンチャン待ち' },
      { tile: '1m',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '9s',  safe: true,  safeType: 'tanpai',  reason: '端牌（比較的安全だが確実ではない）' },
      { tile: '1z',  safe: true,  safeType: 'jihai',   reason: '字牌（刻子/対子のみ使用、比較的安全）' },
    ],
    waits: ['4p', '8p'], waitShape: '3p-5p カンチャン（4p）+ 8p 単騎（複合）',
    explanation: '5p の筋なので 8p が安全そうだが…\n8p 単騎待ちの罠！スジが通用しない。\n白（5z）・中（7z）は現物。字牌（1z）や端牌（1m・9s）が安全。',
    yaku: '清一色', yakuValue: 4,
    playerYaku: '国士無双', playerYakuValue: 5,
  },
];
